name: iOS Build

# 构建环境
image: macos-latest

# 触发条件
trigger:
  push:
    branches:
      - main

# 环境变量
variables:
  XCODE_WORKSPACE: "XGOSAppPhone.xcworkspace"
  XCODE_SCHEME: "XGOSAppPhone"

# 构建步骤
stages:
  - name: 安装依赖
    script:
      - cd XGOSAppPhone
      - pod install

  - name: 构建应用
    script:
      - cd XGOSAppPhone
      - xcodebuild build \
        -workspace $XCODE_WORKSPACE \
        -scheme $XCODE_SCHEME \
        -configuration Release \
        -destination 'generic/platform=iOS' \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO

  - name: 导出 IPA
    script:
      - cd XGOSAppPhone
      - xcodebuild archive \
        -workspace $XCODE_WORKSPACE \
        -scheme $XCODE_SCHEME \
        -configuration Release \
        -archivePath build/XGOSAppPhone.xcarchive \
        -destination 'generic/platform=iOS' \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO
      - xcodebuild -exportArchive \
        -archivePath build/XGOSAppPhone.xcarchive \
        -exportPath build/export \
        -exportOptionsPlist ExportOptions-NoSign.plist

# 构建产物
artifacts:
  paths:
    - XGOSAppPhone/build/export/*.ipa
  expire_in: 7 days