# Codemagic CI/CD 配置文件
# 用于在线构建 iOS 应用

workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        # 配置你的 Apple ID 邮箱
        APP_STORE_CONNECT_ISSUER_ID: ""
        APP_STORE_CONNECT_KEY_IDENTIFIER: ""
        APP_STORE_CONNECT_PRIVATE_KEY: ""
        # 配置你的 Team ID（可以从 Apple Developer 获取）
        XCODE_WORKSPACE: "XGOSAppPhone.xcworkspace"
        XCODE_SCHEME: "XGOSAppPhone"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      # 安装依赖
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/XGOSAppPhone
          pod install --repo-update
      
      # 构建应用
      - name: Build iOS app
        script: |
          cd $CM_BUILD_DIR/XGOSAppPhone
          xcodebuild build \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    
    artifacts:
      - build/Build/Products/Debug-iphonesimulator/*.app
      - build/Build/Products/Debug-iphonesimulator/*.dSYM

# 真机构建配置（需要 Apple ID 和 Team ID）
  ios-device-workflow:
    name: iOS Device Build (Self-Signed)
    environment:
      vars:
        # 配置你的 Apple ID
        APPLE_ID: "your-apple-id@example.com"
        # 配置你的 Apple ID 密码（应用专用密码）
        APPLE_ID_PASSWORD: "your-app-specific-password"
        # 配置你的 Team ID
        TEAM_ID: "YOUR_TEAM_ID"
        XCODE_WORKSPACE: "XGOSAppPhone.xcworkspace"
        XCODE_SCHEME: "XGOSAppPhone"
    scripts:
      # 安装依赖
      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/XGOSAppPhone
          pod install --repo-update
      
      # 配置签名
      - name: Configure code signing
        script: |
          cd $CM_BUILD_DIR/XGOSAppPhone
          # 创建临时 keychain
          security create-keychain -p "" temp.keychain
          security default-keychain -s temp.keychain
          security unlock-keychain -p "" temp.keychain
          security set-keychain-settings -t 3600 -u temp.keychain
          
          # 导入证书（需要上传证书到 Codemagic）
          # security import $HOME/certificates/ios_distribution.cer -k ~/Library/Keychains/temp.keychain -T /usr/bin/codesign
          # security import $HOME/certificates/ios_distribution.p12 -k ~/Library/Keychains/temp.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
      
      # 构建应用
      - name: Build iOS app for device
        script: |
          cd $CM_BUILD_DIR/XGOSAppPhone
          xcodebuild archive \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath build/XGOSAppPhone.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            CODE_SIGNING_REQUIRED=YES \
            CODE_SIGNING_ALLOWED=YES \
            PROVISIONING_PROFILE_SPECIFIER=""
      
      # 导出 IPA
      - name: Export IPA
        script: |
          cd $CM_BUILD_DIR/XGOSAppPhone
          xcodebuild -exportArchive \
            -archivePath build/XGOSAppPhone.xcarchive \
            -exportPath build/export \
            -exportOptionsPlist ExportOptions.plist
    
    artifacts:
      - build/export/*.ipa
      - build/export/*.dSYM